//Write a C program that analyzes cinema revenue using a three-dimensional array. The program should take the number of movies screened per day and the number of screening days as input (ensuring both are positive values). For each screen, record the revenue generated by every movie on each day. Finally, calculate and display the total revenue and average revenue for each screen based on all movies and days of screening.

#include <stdio.h>
#define screens 2

int main()
{
	//Welcome Message
	printf("--------------------Cinema--------------------\n\n");
	
	//Initializing Variables
	int movies,days; 
	
	//Taking Input
	printf("Enter Number Of Movies Screening Per Day: ");
    scanf("%d", &movies);
    while (movies < 1)  //Input Valdiation
    {
        printf("Invalid input! Enter a positive number: ");
        scanf("%d", &movies);
    }

    printf("Enter Number Of Days Of Screening: ");
    scanf("%d", &days);
    while (days < 1) //Input Validation
    {
        printf("Invalid input! Enter a positive number: ");
        scanf("%d", &days);
    }
	
	//Declaring Array
	float revenue[screens][days][movies];
	
	//Taking input for array
	for(int s=0; s<screens; s++)
	{
		printf("\n--------------------Screen %d--------------------\n",s+1);
		for(int d=0; d<days; d++)
		{
			printf("\n---Day %d---\n",d+1);
			for(int m=0; m<movies ;m++)
			{
				printf("Enter Revenue For Movie %d: ",m+1);
				scanf("%f", &revenue[s][d][m]);
			}
		}
	}
	
	//Looping to take sum
	for(int s=0; s<screens; s++)
	{
		float total =0;
		printf("\n--------------------Screen %d--------------------\n",s+1);
		for(int d=0; d<days; d++)
		{
			for(int m=0; m<movies ;m++)
			{
				total += revenue[s][d][m];
				
			}
		}
		
		float average = total/(days*movies);
		printf("Total Revenue: %.2f\n",total);
		printf("Average Reveneue: %.2f\n",average);
	}
	
	return 0;
}